version: '2'

services:
  app:
    image: 'aldfiar/spring-sample-service:latest'
    build:
      context: .
    container_name: services-spring-sample
    depends_on:
      - db
    ports:
      - "9800:9800"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=alanna
      - SPRING_DATASOURCE_PASSWORD=mosvani

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=alanna
      - POSTGRES_PASSWORD=mosvani